In [1]:
import pandas as pd
df = pd.read_csv("main_database_for_models.csv")

In [2]:
df.head()

,season,hPos,hGSPG,hGCPG,hCSPG,hPtsPG,aPos,aGSPG,aGCPG,aCSPG,...,aGD7,hPosLS,aPosLS,hSpent,hIncome,hNet,aSpent,aIncome,aNet,target
0,9,4.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,...,0.0,18,18,18.72,0.479,-18.241,18.07,1.320,-16.750,2
1,9,5.0,0.0,0.0,0.0,0.0,20.0,0.0,0.0,0.0,...,0.0,5,9,47.15,34.830,-12.320,8.92,38.160,29.240,2
2,9,6.0,0.0,0.0,0.0,0.0,15.0,0.0,0.0,0.0,...,0.0,14,12,17.10,23.650,6.550,29.52,9.000,-20.520,0
3,9,7.0,0.0,0.0,0.0,0.0,17.0,0.0,0.0,0.0,...,0.0,16,15,11.99,6.260,-5.730,0.00,0.131,0.131,1
4,9,10.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,...,0.0,3,13,47.84,10.920,-36.920,31.03,32.000,0.970,2

In [3]:
df.columns

Index(['season', 'hPos', 'hGSPG', 'hGCPG', 'hCSPG', 'hPtsPG', 'aPos', 'aGSPG',
       'aGCPG', 'aCSPG', 'aPtsPG', 'hSPG', 'hSTPG', 'aSPG', 'aSTPG', 'hS%',
       'aS%', 'hPTSPG3', 'hPTSPG5', 'hPTSPG7', 'hGD3', 'hGD5', 'hGD7',
       'aPTSPG3', 'aPTSPG5', 'aPTSPG7', 'aGD3', 'aGD5', 'aGD7', 'hPosLS',
       'aPosLS', 'hSpent', 'hIncome', 'hNet', 'aSpent', 'aIncome', 'aNet',
       'target'],
      dtype='object')

In [4]:
def convert_cols_to_difference(row,col1,col2):
    val1 = float(row[col1])
    val2 = float(row[col2])
    new_val = val1-val2
    return round(float(new_val),3)

In [5]:
df['PosDiff'] = df.apply(convert_cols_to_difference,args=('hPos','aPos'),axis=1)
df['GSPGDiff'] = df.apply(convert_cols_to_difference,args=('hGSPG','aGSPG'),axis=1)
df['GCPGDiff'] = df.apply(convert_cols_to_difference,args=('hGCPG','aGCPG'),axis=1)
df['CSPGDiff'] = df.apply(convert_cols_to_difference,args=('hCSPG','aCSPG'),axis=1)
df['PtsPGDiff'] = df.apply(convert_cols_to_difference,args=('hPtsPG','aPtsPG'),axis=1)
# df['ShotDiff'] = df.apply(convert_cols_to_difference,args=('hs2','as2'),axis=1)
df['SPGDiff'] = df.apply(convert_cols_to_difference,args=('hSPG','aSPG'),axis=1)
df['STPGDiff'] = df.apply(convert_cols_to_difference,args=('hSTPG','aSTPG'),axis=1)
df['S%Diff'] = df.apply(convert_cols_to_difference,args=('hS%','aS%'),axis=1)
df['PTSPG3Diff'] = df.apply(convert_cols_to_difference,args=('hPTSPG3','aPTSPG3'),axis=1)
df['PTSPG5Diff'] = df.apply(convert_cols_to_difference,args=('hPTSPG5','aPTSPG5'),axis=1)
df['PTSPG7Diff'] = df.apply(convert_cols_to_difference,args=('hPTSPG7','aPTSPG7'),axis=1)
df['GD3Diff'] = df.apply(convert_cols_to_difference,args=('hGD3','aGD3'),axis=1)
df['GD5Diff'] = df.apply(convert_cols_to_difference,args=('hGD5','aGD5'),axis=1)
df['GD7Diff'] = df.apply(convert_cols_to_difference,args=('hGD7','aGD7'),axis=1)
df['PosLSDiff'] = df.apply(convert_cols_to_difference,args=('hPosLS','aPosLS'),axis=1)
df['SpentDiff'] = df.apply(convert_cols_to_difference,args=('hSpent','aSpent'),axis=1)
df['IncomeDiff'] = df.apply(convert_cols_to_difference,args=('hIncome','aIncome'),axis=1)
df['NetDiff'] = df.apply(convert_cols_to_difference,args=('hNet','aNet'),axis=1)

In [6]:
df.drop(['hPos', 'hGSPG', 'hGCPG', 'hCSPG', 'hPtsPG', 'aPos', 'aGSPG',
       'aGCPG', 'aCSPG', 'aPtsPG', 'hSPG',
       'hSTPG', 'aSPG', 'aSTPG', 'hS%', 'aS%', 'hPTSPG3', 'hPTSPG5', 'hPTSPG7',
       'hGD3', 'hGD5', 'hGD7', 'aPTSPG3', 'aPTSPG5', 'aPTSPG7', 'aGD3', 'aGD5',
       'aGD7', 'hPosLS', 'aPosLS', 'hSpent', 'hIncome', 'hNet', 'aSpent',
       'aIncome', 'aNet'],inplace=True,axis=1)

In [7]:
df.head()

,season,target,PosDiff,GSPGDiff,GCPGDiff,CSPGDiff,PtsPGDiff,SPGDiff,STPGDiff,S%Diff,PTSPG3Diff,PTSPG5Diff,PTSPG7Diff,GD3Diff,GD5Diff,GD7Diff,PosLSDiff,SpentDiff,IncomeDiff,NetDiff
0,9,2,-9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.65,-0.841,-1.491
1,9,2,-15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-4.0,38.23,-3.330,-41.560
2,9,0,-9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,-12.42,14.650,27.070
3,9,1,-10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,11.99,6.129,-5.861
4,9,2,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-10.0,16.81,-21.080,-37.890

In [8]:
df.to_csv("main_database_diffs_for_models.csv",index=False)