In [1]:
%run basic_league_table_generator.ipynb

In [2]:
df = pd.read_csv("data_collected_final_version.csv")

In [3]:
t1 = time.time()
df_season = df.query("season == 26")
teams = df_season['home'].unique().tolist()
final_table = basic_league_table("2018-05-14",df_season,teams)
t2 = time.time()
total = t2-t1
print("Took {} seconds".format(round(total,5)))

Took 0.17192 seconds

In [4]:
final_table

    Pos            Team  GP   W   D   L   GS  GC  GD  CS  Pts
0     1        man city  38  32   4   2  106  27  79  18  100
1     2         man utd  38  25   6   7   68  28  40  19   81
2     3           spurs  38  23   8   7   74  36  38  16   77
3     4       liverpool  38  21  12   5   84  38  46  17   75
4     5         chelsea  38  21   7  10   62  38  24  16   70
5     6         arsenal  38  19   6  13   74  51  23  13   63
6     7         burnley  38  14  12  12   36  39  -3  12   54
7     8         everton  38  13  10  15   44  58 -14  10   49
8     9       leicester  38  12  11  15   56  60  -4   9   47
9    10       newcastle  38  12   8  18   39  47  -8   9   44
10   11  crystal palace  38  11  11  16   45  55 -10   9   44
11   12     bournemouth  38  11  11  16   45  61 -16   6   44
12   13        west ham  38  10  12  16   48  68 -20  10   42
13   14         watford  38  11   8  19   44  64 -20   9   41
14   15        brighton  38   9  13  16   34  54 -20  10   40
15   16    huddersfield  38   9  10  19   28  58 -30  10   37
16   17     southampton  38   7  15  16   37  56 -19   8   36
17   18         swansea  38   8   9  21   28  56 -28   9   33
18   19           stoke  38   7  12  19   35  68 -33   6   33
19   20       west brom  38   6  13  19   31  56 -25  10   31

In [5]:
final_table.to_csv("table_end_of_data.csv",index=False)